### ISSUE TITLE
Turnkey issues

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon-terraform#15]
- [x] ECR: image does not exist in the beginning (needs to run CodeBuild) #20 
- [x] Add configurable CIDR range for SSH
- [ ] Create presets when run scripts (2 points)
- [x] Fix preset template (currently returning 2 extra nils)
- [x] Create dropbox folder if not exist
- [x] Add Manage Jobs to Admin view
- [x] Add timeliner setting to Terraform script
- [ ] Missing controlled_vocabulary.yml (1 point)

**Comment by joncameron** [comment]
Phuong will break this out when read, as needed.

**Comment by joncameron** [comment]
I will break out the two remaining tasks.

**Comment by joncameron** [comment]
Closing—new tasks broken off are #25 and #26 in avalon-terraform
