### ISSUE TITLE
Please publish custom AMI to other regions

### ISSUE THREAD

**Issue by SolomonHD** [avalonmediasystem/avalon-terraform#17]
Hello,

I am trying to run this in us-west-2 but the hard coded ami (ami-08b255f35f032a5ea) is us-east-1. I've tried using the ami_copy resource in terraform but it says I don't have access permissions on the ami

**Comment by phuongdh** [comment]
@SolomonHD I've copied the AMI to us-west-2, its ID will be `ami-070dfb59a46d7e81e` when it's done copying. I plan to use an off-the-shelves one #18

**Comment by SolomonHD** [comment]
Thanks for the quick response!
