### ISSUE TITLE
ERROR: for worker [...] no basic auth credentials 

### ISSUE THREAD

**Issue by SolomonHD** [avalonmediasystem/avalon-terraform#19]
I'm having issues running this in us-east-1 region. I get this error during the null_resource.install_docker_on_compose step
``` Pulling hls    ... doneus: downloaded newer image fo...
null_resource.install_docker_on_compose (remote-exec): Pulling hls    ... doneus: downloaded newer image fo...
null_resource.install_docker_on_compose (remote-exec):
null_resource.install_docker_on_compose (remote-exec): ERROR: for worker  Get https://[aws account number].dkr.ecr.us-east-1.amazonaws.com/v2/avalon/manifests/latest: no basic auth credentials

null_resource.install_docker_on_compose (remote-exec): ERROR: for avalon  Get https://[aws account number].dkr.ecr.us-east-1.amazonaws.com/v2/avalon/manifests/latest: no basic auth credentials
null_resource.install_docker_on_compose (remote-exec): ERROR: Get https://[aws account number].dkr.ecr.us-east-1.amazonaws.com/v2/avalon/manifests/latest: no basic auth credentials
null_resource.install_docker_on_compose (remote-exec): Get https://[aws account number].dkr.ecr.us-east-1.amazonaws.com/v2/avalon/manifests/latest: no basic auth credentials
```

Docker seems to be logging in fine with the `aws ecr get-login` command so I don't know what's going on here.  Perhaps it's trying to push to this repo?

**Comment by phuongdh** [comment]
@SolomonHD I'll take a look. Probably a bug when we switched to ECR recently. I think it's trying to pull from ECR before the image exists.

**Comment by SolomonHD** [comment]
Again thanks for the quick response, I'm new to docker. Is there something special about the hls image that causes it to fail? It seems to pull down the fedora image w/o issue.

**Comment by phuongdh** [comment]
It was the Avalon image, not the hls image that failed. In the mean time I believe you can go to CodeBuild and start a build now, it should build and push the Avalon image properly to ECR.

**Comment by SolomonHD** [comment]
I'm sorry I don't understand your instructions. Like I said I'm new to docker.

Would you be free to discuss this on Zoom tomorrow (Friday)?

**Comment by phuongdh** [comment]
@SolomonHD CodeBuild is an AWS service. You'd need to navigate to your project and click the Start build button. If there's any problem feel free to DM on Slack and we can share screen.

![image](https://user-images.githubusercontent.com/1304657/91577833-4cc94580-e917-11ea-8278-7c84df3309ec.png)

**Comment by phuongdh** [comment]
@SolomonHD I made some changes to our Terraform script to address your issues: use generic Amazon Linux 2 and build Avalon on deploy. Please try this new branch and let me know of any problem https://github.com/avalonmediasystem/avalon-terraform/tree/generic-ami. Thanks!

**Comment by SolomonHD** [comment]
There seems to be an issue with the local-exec function not being able to access the credentials of the terminal running terraform. The command is failing at `aws codebuild start-build --project-name ${aws_codebuild_project.docker.name}`
At first it said no region specified, so I changed the line to `aws codebuild start-build --project-name ${aws_codebuild_project.docker.name} --region ${var.aws_region}`

Now the error is `exit status 255. Output: Unable to locate credentials. You can configure credentials by running "aws configure"`

**Comment by phuongdh** [comment]
@SolomonHD I couldn't find any Terraform module that lets you _start_ a build. From what I've read your linked module also creates the project only.

That error is strange because it should use your locally setup AWS config and credentials in ~/.aws/. Do you have these setup?

Re: ETA2, does that mean the command went through?

**Comment by SolomonHD** [comment]
On ETA2, it means that I still needed to hit the Start Build button on the AWS Console, it's just that the step where we logged into the EC2 and ran docker-compose up -d wasn't needed anymore, avalon came up after the build was started.

I have my aws credentials setup correctly as far as I know. Currently I'm providing main.tf with:
``` hcl
provider "aws" {
  profile = "myprofile"
  region = "us-east-1"
}
```
Should I also `export AWS_PROFILE=myprofile` as an env var before running terraform?

**Comment by phuongdh** [comment]
It should be `local-exec` because only you, not the EC2 role should have permission to start a build. If you can run that awscli command outside of Terraform then you should be able to run it inside Terraform. 

Although if you're using a non-default profile then you have to add `--profile myprofile` to the `local-exec` or set AWS_PROFILE before running Terraform, because `local-exec` is a null provider and doesn't know about the profile in aws provider. 

I'll add support for non-default profile.

**Comment by SolomonHD** [comment]
Please do thank you! I don't use aws_default_profile because I find it's buggy and I have multiple accounts I have to manage 😭

**Comment by phuongdh** [comment]
I [added a commit](https://github.com/avalonmediasystem/avalon-terraform/commit/50dfde9026371f72acaf3b7c4487e8077b552287) to do just that. You'll have to configure the `aws_profile` variable in your `.tfvars` file.

**Comment by SolomonHD** [comment]
I just tested this change with aws_profile set correctly and it worked! The build now starts by itself and avalon comes up after the build is completed! Great work. If you merge this into master I can test your other change with the default user.

**Comment by SolomonHD** [comment]
Actually one more small change; can you add the --region ${var.aws_region} to that line as well? Without it goes with whatever you have set for the profile, it ignores the aws_region in the template itself

**Comment by phuongdh** [comment]
I added the region as well. Thanks for the feedback.

**Comment by SolomonHD** [comment]
Did you mean to reopen this @phuongdh?

**Comment by phuongdh** [comment]
> Did you mean to reopen this @phuongdh?

I closed by accident. The way zenhub is setup, stories don't get closed until we finish the sprint.
