### ISSUE TITLE
ECR Error when attempting to build 2nd environment

### ISSUE THREAD

**Issue by SolomonHD** [avalonmediasystem/avalon-terraform#21]
I am having issues building an environment while another environment already exists.

I am using s3 backend with separate workspaces, so environments should not be stepping on each other's toes.

I get this error when building the 2nd environment:

`Error: error creating ECR repository: RepositoryAlreadyExistsException: The repository with name 'avalon' already exists in the registry with id '[aws account number]'`

Perhaps something is hard coded to avalon when it should be avalon-[env]?

**Comment by SolomonHD** [comment]
I think the issue is here:
```hcl
resource "aws_ecr_repository" "avalon" {
  name                 = "avalon"
  image_tag_mutability = "MUTABLE"

  tags = local.common_tags
}
```
Shouldn't `name = "avalon-${var.environment}"`?

**Comment by phuongdh** [comment]
@SolomonHD that's right. If that change works feel free to create a PR. Thanks.

**Comment by joncameron** [comment]
@phuongdh has approved the submitted PR; closing.
