### ISSUE TITLE
docker-compose pull - no basic auth credentials

### ISSUE THREAD

**Issue by izixsun** [avalonmediasystem/avalon-terraform#30]
Errors for avalon and worker when trying to pull - no basic auth credentials

My experience with both docker-compose and AWS is limited and I'm not sure if I'm missing something I should know, or if this is an issue with the code.  I have found a work around and am posting in the interest of helping others that may encounter this issue.

I am able to pull after logging in with the following when providing the specifics for my account # and the region:

aws ecr get-login-password --region (region) | docker login --username AWS --password-stdin (account #).dkr.ecr.(region).amazonaws.com

**Comment by phuongdh** [comment]
@izixsun when does the above error happen? Can you provide more logging around that error?

**Comment by izixsun** [comment]
Hi
Here are the steps that get me there.  Terraform apply works as expected then I log into the instance and call docker-compose pull:

[ec2-user@ip-10-1-2-9 avalon-docker-aws_min]$ docker-compose pullPulling fedora    ... donePulling s3-helper ... donePulling solr      ... donePulling jobs      ... donePulling cache     ... donePulling avalon    ... errorPulling hls       ... donePulling worker    ... error
ERROR: for avalon  Get https://000000000000.dkr.ecr.us-east-1.amazonaws.com/v2/avalon-dev/manifests/latest: no basic auth credentials
ERROR: for worker  Get https://000000000000.dkr.ecr.us-east-1.amazonaws.com/v2/avalon-dev/manifests/latest: no basic auth credentials


I've looked for a log, but didn't find one.  If you tell me where to look I will pull the detail that's helpful.  
 
 
 


@izixsun when does the above error happen? Can you provide more logging around that error?

**Comment by phuongdh** [comment]
@izixsun ybecause ECR is a private container registry, you are expected to login to it before being able to pull. Btw, you should use CodeBuild to build and deploy changes your instance instead of doing it manually.
